import { Competency } from "../types";

export const EXCEL_COMPETENCIES: Competency[] = [
  {
    id: "xl-navigation-basics",
    domainId: "excel-pro",
    title: "Workbook Navigation and Data Formatting",
    description: "Grid structure, cell references (relative, absolute, mixed $A$1), cell formatting, and keyboard shortcuts.",
    category: "PROCEDURAL",
    prerequisites: [],
    difficulty: 1,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "xl-core-math-functions",
    domainId: "excel-pro",
    title: "Basic Aggregation Functions",
    description: "SUM, AVERAGE, MIN, MAX, COUNT, and COUNTA calculations over ranges.",
    category: "PROCEDURAL",
    prerequisites: ["xl-navigation-basics"],
    difficulty: 1,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "xl-logical-formulas",
    domainId: "excel-pro",
    title: "Logical Formulas (IF, AND, OR)",
    description: "Single and nested IF statements, boolean conditions using AND, OR, and NOT, IFS function.",
    category: "CONCEPTUAL",
    prerequisites: ["xl-core-math-functions"],
    difficulty: 2,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "xl-conditional-math",
    domainId: "excel-pro",
    title: "Conditional Aggregations (SUMIFS, COUNTIFS)",
    description: "Filtering calculations by single and multiple criteria using SUMIF, SUMIFS, COUNTIF, and COUNTIFS.",
    category: "PROCEDURAL",
    prerequisites: ["xl-logical-formulas"],
    difficulty: 2,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "xl-lookup-functions",
    domainId: "excel-pro",
    title: "Lookup and Reference (XLOOKUP, INDEX/MATCH)",
    description: "Modern search with XLOOKUP, legacy VLOOKUP limitations, two-way lookups with INDEX and MATCH.",
    category: "PROCEDURAL",
    prerequisites: ["xl-logical-formulas"],
    difficulty: 3,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "xl-text-data-cleaning",
    domainId: "excel-pro",
    title: "Text Manipulation and Data Cleaning",
    description: "TRIM, CLEAN, CONCAT/TEXTJOIN, LEFT, RIGHT, MID, Flash Fill, and Text-to-Columns.",
    category: "PROCEDURAL",
    prerequisites: ["xl-navigation-basics"],
    difficulty: 2,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "xl-pivot-tables",
    domainId: "excel-pro",
    title: "Pivot Tables and Data Summaries",
    description: "Creating Pivot Tables, rows, columns, values, grouping dates, calculated fields, and slicers.",
    category: "PROCEDURAL",
    prerequisites: ["xl-conditional-math", "xl-text-data-cleaning"],
    difficulty: 3,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "xl-visualization-validation",
    domainId: "excel-pro",
    title: "Data Visualization and Validation",
    description: "Dynamic charting, sparklines, conditional formatting rule management, and dropdown data validation.",
    category: "PROCEDURAL",
    prerequisites: ["xl-pivot-tables", "xl-lookup-functions"],
    difficulty: 3,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
];
