import { Competency } from "../types";

export const MATHEMATICS_COMPETENCIES: Competency[] = [
  {
    id: "math-algebraic-expressions",
    domainId: "math-exams",
    title: "Algebraic Expressions and Operations",
    description: "Evaluating expressions, combining like terms, expanding brackets, and basic factoring.",
    category: "CONCEPTUAL",
    prerequisites: [],
    difficulty: 1,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "math-linear-equations",
    domainId: "math-exams",
    title: "Linear Equations in One Variable",
    description: "Solving single-variable equations, isolating variables, and word-problem translation.",
    category: "PROCEDURAL",
    prerequisites: ["math-algebraic-expressions"],
    difficulty: 2,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "math-linear-systems",
    domainId: "math-exams",
    title: "Systems of Linear Equations",
    description: "Solving two-variable linear systems via substitution, elimination, and graphical intersection.",
    category: "PROCEDURAL",
    prerequisites: ["math-linear-equations"],
    difficulty: 3,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "math-quadratic-equations",
    domainId: "math-exams",
    title: "Quadratic Equations",
    description: "Factoring quadratic trinomials, completing the square, and using the quadratic formula.",
    category: "CONCEPTUAL",
    prerequisites: ["math-algebraic-expressions"],
    difficulty: 3,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "math-functions-graphs",
    domainId: "math-exams",
    title: "Functions and Graphs",
    description: "Function notation f(x), domain and range, slope-intercept form, and parabola vertices.",
    category: "CONCEPTUAL",
    prerequisites: ["math-linear-systems", "math-quadratic-equations"],
    difficulty: 3,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "math-trigonometry-ratios",
    domainId: "math-exams",
    title: "Trigonometric Ratios and Right Triangles",
    description: "Sine, cosine, and tangent ratios in right triangles; Pythagorean theorem applications.",
    category: "FACTUAL",
    prerequisites: ["math-algebraic-expressions"],
    difficulty: 3,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "math-coordinate-geometry",
    domainId: "math-exams",
    title: "Coordinate Geometry",
    description: "Distance formula, midpoint formula, parallel and perpendicular lines, equation of a circle.",
    category: "PROCEDURAL",
    prerequisites: ["math-functions-graphs", "math-trigonometry-ratios"],
    difficulty: 4,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "math-probability-statistics",
    domainId: "math-exams",
    title: "Foundational Probability and Descriptive Statistics",
    description: "Sample spaces, compound events, mean, median, mode, variance, and standard deviation.",
    category: "CONCEPTUAL",
    prerequisites: ["math-algebraic-expressions"],
    difficulty: 2,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
];
