import { Competency } from "../types";

export const PYTHON_COMPETENCIES: Competency[] = [
  {
    id: "py-variables-types",
    domainId: "python-junior",
    title: "Variables and Primitive Data Types",
    description: "Understanding variables, memory assignment, and core data types: int, float, str, and bool.",
    category: "CONCEPTUAL",
    prerequisites: [],
    difficulty: 1,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "py-operators-expressions",
    domainId: "python-junior",
    title: "Operators and Expressions",
    description: "Arithmetic, comparison, and boolean logical operators; operator precedence.",
    category: "PROCEDURAL",
    prerequisites: ["py-variables-types"],
    difficulty: 1,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "py-conditionals",
    domainId: "python-junior",
    title: "Conditional Branching",
    description: "Decision making using if, elif, and else statements, and nested conditionals.",
    category: "CONCEPTUAL",
    prerequisites: ["py-operators-expressions"],
    difficulty: 2,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "py-loops-iteration",
    domainId: "python-junior",
    title: "Loops and Iteration",
    description: "Definite iteration with for-loops, indefinite iteration with while-loops, break and continue.",
    category: "PROCEDURAL",
    prerequisites: ["py-conditionals"],
    difficulty: 2,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "py-functions-scope",
    domainId: "python-junior",
    title: "Functions and Variable Scope",
    description: "Function definitions, parameters, return values, default arguments, and local vs global scope.",
    category: "CONCEPTUAL",
    prerequisites: ["py-conditionals"],
    difficulty: 3,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "py-data-structures-lists-tuples",
    domainId: "python-junior",
    title: "Lists and Tuples",
    description: "Sequential collections, indexing, slicing, mutability vs immutability, list comprehensions.",
    category: "PROCEDURAL",
    prerequisites: ["py-loops-iteration", "py-functions-scope"],
    difficulty: 3,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "py-data-structures-dicts-sets",
    domainId: "python-junior",
    title: "Dictionaries and Sets",
    description: "Key-value mapping, hashability, dictionary methods, and unique set operations.",
    category: "CONCEPTUAL",
    prerequisites: ["py-data-structures-lists-tuples"],
    difficulty: 3,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "py-error-handling",
    domainId: "python-junior",
    title: "Error and Exception Handling",
    description: "Handling runtime exceptions with try, except, else, and finally blocks; raising custom exceptions.",
    category: "PROCEDURAL",
    prerequisites: ["py-functions-scope"],
    difficulty: 3,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "py-file-io",
    domainId: "python-junior",
    title: "File Input and Output",
    description: "Reading and writing text and structured files using context managers (with open).",
    category: "PROCEDURAL",
    prerequisites: ["py-error-handling", "py-data-structures-dicts-sets"],
    difficulty: 3,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "py-oop-basics",
    domainId: "python-junior",
    title: "Object-Oriented Programming Basics",
    description: "Classes, objects, constructors (__init__), attributes, methods, and encapsulation.",
    category: "CONCEPTUAL",
    prerequisites: ["py-functions-scope", "py-data-structures-dicts-sets"],
    difficulty: 4,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
  {
    id: "py-testing-debugging",
    domainId: "python-junior",
    title: "Unit Testing and Debugging",
    description: "Writing automated tests with pytest/unittest, assertions, test discovery, and pdb debugging.",
    category: "PROCEDURAL",
    prerequisites: ["py-oop-basics", "py-error-handling"],
    difficulty: 4,
    version: 1,
    status: "ACTIVE",
    provenance: "CURATED",
  },
];
