import { DiagnosticItem } from "../types";

export const EXCEL_DIAGNOSTIC_ITEMS: DiagnosticItem[] = [
  {
    id: "diag-xl-nav-1",
    domainId: "excel-pro",
    competencyId: "xl-navigation-basics",
    prompt: "In Excel, which reference style locks BOTH the column and the row when copied across cells?",
    itemType: "MULTIPLE_CHOICE",
    difficulty: 1,
    options: ["$A1", "A$1", "$A$1", "A1"],
    correctAnswer: "$A$1",
    explanation: "$A$1 is an absolute reference locking both column A and row 1.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-xl-math-1",
    domainId: "excel-pro",
    competencyId: "xl-core-math-functions",
    prompt: "Which function counts the number of cells in range A1:A10 containing ANY non-empty value (text or numbers)?",
    itemType: "SHORT_ANSWER",
    difficulty: 1,
    correctAnswer: "COUNTA",
    explanation: "COUNTA counts non-empty cells, whereas COUNT only counts numeric cells.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-xl-logic-1",
    domainId: "excel-pro",
    competencyId: "xl-logical-formulas",
    prompt: "What is the result of `=IF(AND(5 > 3, 2 < 1), 'Pass', 'Fail')`?",
    itemType: "MULTIPLE_CHOICE",
    difficulty: 2,
    options: ["Pass", "Fail", "#VALUE!", "TRUE"],
    correctAnswer: "Fail",
    explanation: "AND(5 > 3, 2 < 1) evaluates to FALSE because 2 < 1 is false; therefore the IF returns 'Fail'.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-xl-cond-1",
    domainId: "excel-pro",
    competencyId: "xl-conditional-math",
    prompt: "Which function allows summing values in column C where column A is 'North' AND column B is > 100?",
    itemType: "SHORT_ANSWER",
    difficulty: 2,
    correctAnswer: "SUMIFS",
    explanation: "SUMIFS supports multiple criteria across multiple ranges.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-xl-look-1",
    domainId: "excel-pro",
    competencyId: "xl-lookup-functions",
    prompt: "Unlike VLOOKUP, which parameter in XLOOKUP allows you to specify a fallback value directly without wrapping in IFERROR?",
    itemType: "MULTIPLE_CHOICE",
    difficulty: 3,
    options: ["match_mode", "if_not_found", "search_mode", "lookup_array"],
    correctAnswer: "if_not_found",
    explanation: "The 4th argument of XLOOKUP is [if_not_found], which directly handles missing keys.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-xl-piv-1",
    domainId: "excel-pro",
    competencyId: "xl-pivot-tables",
    prompt: "In a Pivot Table, what area should numeric revenue metrics typically be dragged into to calculate totals?",
    itemType: "MULTIPLE_CHOICE",
    difficulty: 2,
    options: ["Filters", "Rows", "Columns", "Values"],
    correctAnswer: "Values",
    explanation: "The Values area aggregates numeric fields into sums, averages, or counts.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
];
