import { DiagnosticItem } from "../types";

export const MATHEMATICS_DIAGNOSTIC_ITEMS: DiagnosticItem[] = [
  {
    id: "diag-math-alg-1",
    domainId: "math-exams",
    competencyId: "math-algebraic-expressions",
    prompt: "Expand and simplify the algebraic expression: `(2x + 3)(x - 4)`",
    itemType: "MULTIPLE_CHOICE",
    difficulty: 2,
    options: ["2x^2 - 5x - 12", "2x^2 + 5x - 12", "2x^2 - 8x - 12", "2x^2 - 5x + 12"],
    correctAnswer: "2x^2 - 5x - 12",
    explanation: "2x*x - 8x + 3x - 12 = 2x^2 - 5x - 12.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-math-lin-1",
    domainId: "math-exams",
    competencyId: "math-linear-equations",
    prompt: "Solve the linear equation for x: `3x - 7 = 2(x + 4)`",
    itemType: "NUMERIC",
    difficulty: 2,
    correctAnswer: "15",
    explanation: "3x - 7 = 2x + 8 => 3x - 2x = 8 + 7 => x = 15.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-math-quad-1",
    domainId: "math-exams",
    competencyId: "math-quadratic-equations",
    prompt: "What is the discriminant value of the quadratic equation `x^2 - 6x + 9 = 0`?",
    itemType: "NUMERIC",
    difficulty: 3,
    correctAnswer: "0",
    explanation: "Discriminant D = b^2 - 4ac = (-6)^2 - 4(1)(9) = 36 - 36 = 0 (one repeated root).",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-math-sys-1",
    domainId: "math-exams",
    competencyId: "math-linear-systems",
    prompt: "For the system `x + y = 10` and `x - y = 4`, what is the value of x?",
    itemType: "NUMERIC",
    difficulty: 3,
    correctAnswer: "7",
    explanation: "Adding both equations gives 2x = 14 => x = 7.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-math-trig-1",
    domainId: "math-exams",
    competencyId: "math-trigonometry-ratios",
    prompt: "In a right triangle with acute angle theta, if the opposite side is 3 and the hypotenuse is 5, what is sin(theta)?",
    itemType: "SHORT_ANSWER",
    difficulty: 2,
    correctAnswer: "0.6",
    explanation: "sin(theta) = opposite / hypotenuse = 3/5 = 0.6.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-math-stat-1",
    domainId: "math-exams",
    competencyId: "math-probability-statistics",
    prompt: "What is the median of the following dataset: `[3, 8, 2, 10, 5]`?",
    itemType: "NUMERIC",
    difficulty: 2,
    correctAnswer: "5",
    explanation: "Sorted dataset is [2, 3, 5, 8, 10]. The middle element is 5.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
];
