import { DiagnosticItem } from "../types";

export const PYTHON_DIAGNOSTIC_ITEMS: DiagnosticItem[] = [
  {
    id: "diag-py-var-1",
    domainId: "python-junior",
    competencyId: "py-variables-types",
    prompt: "In Python, what is the data type of the expression `type(4.0 / 2)`?",
    itemType: "MULTIPLE_CHOICE",
    difficulty: 1,
    options: ["<class 'int'>", "<class 'float'>", "<class 'number'>", "<class 'double'>"],
    correctAnswer: "<class 'float'>",
    explanation: "Division `/` in Python 3 always produces a float, even if operands divide evenly.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-py-cond-1",
    domainId: "python-junior",
    competencyId: "py-conditionals",
    prompt: "What will be printed by the following code?\n```python\nx = 10\nif x > 5 and x < 10:\n    print('A')\nelif x == 10:\n    print('B')\nelse:\n    print('C')\n```",
    itemType: "MULTIPLE_CHOICE",
    difficulty: 2,
    options: ["A", "B", "C", "None of the above"],
    correctAnswer: "B",
    explanation: "x is 10, so the first condition is false (x < 10 is false). The elif condition x == 10 is true.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-py-loop-1",
    domainId: "python-junior",
    competencyId: "py-loops-iteration",
    prompt: "How many times does the following loop print 'hello'?\n```python\nfor i in range(2, 8, 2):\n    print('hello')\n```",
    itemType: "NUMERIC",
    difficulty: 2,
    correctAnswer: "3",
    explanation: "range(2, 8, 2) produces the sequence: 2, 4, 6 (3 values).",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-py-func-1",
    domainId: "python-junior",
    competencyId: "py-functions-scope",
    prompt: "What will be the output of `foo()`?\n```python\ndef foo(items=[]):\n    items.append(1)\n    return len(items)\nfoo()\nprint(foo())\n```",
    itemType: "NUMERIC",
    difficulty: 3,
    correctAnswer: "2",
    explanation: "Default list arguments in Python are evaluated once at function definition time and mutated across calls.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-py-ds-1",
    domainId: "python-junior",
    competencyId: "py-data-structures-lists-tuples",
    prompt: "What is the value of `lst[1:4]` if `lst = [10, 20, 30, 40, 50]`?",
    itemType: "MULTIPLE_CHOICE",
    difficulty: 2,
    options: ["[20, 30, 40]", "[10, 20, 30]", "[20, 30, 40, 50]", "[10, 20, 30, 40]"],
    correctAnswer: "[20, 30, 40]",
    explanation: "Slicing lst[1:4] extracts indices 1, 2, and 3: [20, 30, 40].",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-py-err-1",
    domainId: "python-junior",
    competencyId: "py-error-handling",
    prompt: "Which clause in a Python try/except statement executes only when NO exception was raised in the try block?",
    itemType: "SHORT_ANSWER",
    difficulty: 3,
    correctAnswer: "else",
    explanation: "The `else` clause in a try block runs if no exception occurred.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
  {
    id: "diag-py-oop-1",
    domainId: "python-junior",
    competencyId: "py-oop-basics",
    prompt: "In a Python class method, what does the first parameter convention `self` represent?",
    itemType: "MULTIPLE_CHOICE",
    difficulty: 3,
    options: [
      "The class definition itself",
      "The specific instance of the class",
      "A global reference pointer",
      "The superclass constructor",
    ],
    correctAnswer: "The specific instance of the class",
    explanation: "`self` represents the instance of the class on which the method is invoked.",
    version: 1,
    provenance: "CURATED",
    status: "ACTIVE",
  },
];
